name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - uses: aquiladev/ipfs-action@v0.1.1
        id: upload
        with:
          path: ./build
      - uses: aquiladev/ipfs-action@v0.1.3
        id: pinata
        with:
          path: ./build
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          pinataPinName: "pin_name"
