name: CI

on:
  push:
    branches: [ main ]

jobs:
  upload-ipfs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: aquiladev/ipfs-action@v0.1.1
        with:
          path: ./
      
      - uses: aquiladev/ipfs-action@v0.1.1
        id: ipfs
        with:
          path: ./build
          host: ipfs.komputing.org
          port: 443
          protocol: https
          timeout: 180000
          verbose: true

      - uses: aquiladev/ipfs-action@v0.1.1
        with:
          path: ./build
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
      

      # - uses: aquiladev/ipfs-action@v0.1.1
      #   id: upload
      #   with:
      #     path: ./build
      # - uses: aquiladev/ipfs-action@v0.1.3
      #   id: pinata
      #   with:
      #     path: ./build
      #     service: pinata
      #     pinataKey: ${{ secrets.PINATA_KEY }}
      #     pinataSecret: ${{ secrets.PINATA_SECRET }}
      #     pinataPinName: "pin_name"
